server:
  port: 8762
#  port: 8763

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eurka-client
