spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
  jpa:
    hibernate:
#    这里要注意否则会使得初始化的数据丢失
      ddl-auto: update
