DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NOT NULL COMMENT '用户名',
	username VARCHAR (30) NOT NULL COMMENT '账号',
	password VARCHAR(50) NOT NULL COMMENT '密码',
	PRIMARY KEY (id)
);
